@startuml

actor       User   
participant Display 
participant Door
participant RFIDReader
participant StationControl
participant ChargeControl
participant LogFile

User -> Door : opens 

Door -> StationControl : << Door Open >>
activate StationControl

StationControl -> Display : Show: "Connect your phone"
deactivate StationControl

User -> ChargeControl : connects phone

User -> Door : closes


Door -> StationControl : << Door Closed >>
activate StationControl

StationControl -> Display : Show: "Scan RFID"
deactivate StationControl

   loop If Phone Not Connected

    User -> RFIDReader : scans rfid

    RFIDReader -> StationControl : << RFID Detected >>
    activate StationControl

    StationControl -> ChargeControl : << Is Connected >>
    activate ChargeControl

    ChargeControl -> StationControl : << false >>

    StationControl -> Display : Show "Your phone is not connected properly. Try again"

    end

    ChargeControl -> StationControl : << true >>
    deactivate ChargeControl

    StationControl -> ChargeControl : << Start Charge >>
  loop If Phone Connected
    alt If 5 mA < Current <= 500 mA  
      ChargeControl -> Display : Show "Phone is charging"
    else If Current > 500 mA
      ChargeControl -> Display : "ERROR: Potential short circuit. Disconnect phone immediately."
    else If 0 mA < Current <= 5 mA
      StationControl -> Display : Show "Phone fully charged. It can be safely removed."
    end 
  end
    StationControl -> Door : << Lock Door >>

    StationControl -> LogFile : << Log Door ID >>

    StationControl -> Display : Show "The locker is locked. Use your RFID tag to unlock it."
    deactivate StationControl

  loop If RFID Wrong    

    User -> RFIDReader : scans rfid

    RFIDReader -> StationControl : << RFID Detected >>
    activate StationControl

    
    StationControl -> StationControl : << Check ID >>
    activate StationControl
    

    deactivate StationControl
    StationControl -> StationControl : << false >>

    StationControl -> Display : Show "Wrong RFID tag"
   end

    StationControl -> StationControl : true
    activate StationControl
    

    deactivate StationControl

 
    StationControl -> ChargeControl : << Stop Charge >>

    StationControl -> Door : << Unlock Door >>

    StationControl -> LogFile : << Log Door ID

    StationControl -> Display : Show "Grab your phone and close the door"
    
    deactivate StationControl
@enduml